In [8]:
!pip install torch
import torch

In [ ]:
# tensor is just an n-dimension array
x = torch.tensor([[1, 0], 
                  [1, 0]])
print(x)
print(x.shape)

y = torch.tensor([[2, 2], 
                  [2, 1]])
print(y)
print(y.shape)

tensor([[1, 0],
        [1, 0]])
torch.Size([2, 2])
tensor([[2, 2],
        [2, 1]])
torch.Size([2, 2])


In [18]:
# Multiply two matrices with torch.chain_matmul
z = torch.matmul(x, y)
print(z)

tensor([[2, 2],
        [2, 2]])


In [ ]:
# Relu
t = torch.tensor([-3.0, -1.0, 0.0, 2.0, 5.0])                                                            
print(torch.relu(t))
# it sets each negative value to 0 but keeps their position
# im not sure why neural nets need it. what is non linearity?
    # Basically, setting numbers to zero allows for it to learn curves that aren't linear

tensor([0., 0., 0., 2., 5.])


In [33]:
# Simple neuron
weights = torch.tensor([[0.5, 0.7]
                       ,[0.2, 0.3]])
inputs = torch.tensor([1.0, 2.0])
bias = torch.tensor([0.1, 0.2])

output = torch.relu(torch.matmul(weights, inputs) + bias)

print(output)


tensor([2., 1.])
